import openapiTS, { astToString } from 'openapi-typescript';
import * as fs from 'node:fs/promises';
import * as path from 'node:path';

export interface GeneratorOptions {
  /** URL or file path to OpenAPI 3.0 spec (JSON or YAML) */
  input: string;
  /** Output file path for the generated TypeScript file */
  output: string;
}

/**
 * Generates TypeScript types and a light API Client wrapper from an OpenAPI spec.
 */
export async function generateSDK(options: GeneratorOptions): Promise<void> {
  const { input, output } = options;

  console.log(`Fetching and parsing spec from: ${input}...`);

  // 1. Generate full TypeScript interfaces from OpenAPI spec AST
  const ast = await openapiTS(input);
  const typeDefinitions = astToString(ast);

  // 2. Lightweight typed fetch SDK wrapper code
  const sdkWrapperCode = `
/* ==========================================================================
   Lightweight SDK Client Boilerplate
   ========================================================================== */

export interface ClientOptions {
  baseUrl: string;
  headers?: Record<string, string>;
  fetch?: typeof globalThis.fetch;
}

export class ApiClient {
  private baseUrl: string;
  private headers: Record<string, string>;
  private fetchApi: typeof globalThis.fetch;

  constructor(options: ClientOptions) {
    this.baseUrl = options.baseUrl.replace(/\\/+$/, '');
    this.headers = options.headers || {};
    this.fetchApi = options.fetch || globalThis.fetch.bind(globalThis);
  }

  async request<T>(
    method: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH',
    path: string,
    options: {
      params?: Record<string, string | number | boolean>;
      body?: unknown;
      headers?: Record<string, string>;
    } = {}
  ): Promise<T> {
    const url = new URL(this.baseUrl + path);
    
    if (options.params) {
      Object.entries(options.params).forEach(([key, value]) => {
        if (value !== undefined) {
          url.searchParams.append(key, String(value));
        }
      });
    }

    const response = await this.fetchApi(url.toString(), {
      method,
      headers: {
        'Content-Type': 'application/json',
        ...this.headers,
        ...options.headers,
      },
      body: options.body ? JSON.stringify(options.body) : undefined,
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(\`[HTTP \${response.status}] \${response.statusText}: \${errorText}\`);
    }

    if (response.status === 204) {
      return {} as T;
    }

    return response.json() as Promise<T>;
  }
}
`;

  // 3. Combine generated AST types and SDK wrapper
  const fileContent = `/**
 * This file was auto-generated by openapi-sdk-gen.
 * Do not edit this file directly.
 */

${typeDefinitions}

${sdkWrapperCode}
`;

  const absoluteOutputPath = path.resolve(process.cwd(), output);
  await fs.mkdir(path.dirname(absoluteOutputPath), { recursive: true });
  await fs.writeFile(absoluteOutputPath, fileContent, 'utf-8');

  console.log(`✅ SDK successfully generated at: ${absoluteOutputPath}`);
}
